
CREATE TABLE public.story_likes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    story_id uuid NOT NULL REFERENCES public.stories(id) ON DELETE CASCADE,
    UNIQUE (user_id, story_id)
);

ALTER TABLE public.story_likes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON public.story_likes FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users" ON public.story_likes FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Enable delete for users based on user_id" ON public.story_likes FOR DELETE USING (auth.uid() = user_id);


CREATE TABLE public.story_comments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    story_id uuid NOT NULL REFERENCES public.stories(id) ON DELETE CASCADE,
    comment text NOT NULL
);

ALTER TABLE public.story_comments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON public.story_comments FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users" ON public.story_comments FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Enable update for users based on user_id" ON public.story_comments FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Enable delete for users based on user_id" ON public.story_comments FOR DELETE USING (auth.uid() = user_id);
